networks:
  kafka-net:
    name: kafka-net
    driver: bridge
  api-net:
    name: api-net
    driver: bridge

services:

  backend-worker-rotate:
    container_name: backend-worker-rotate
    networks:
      - kafka-net
      - api-net
    build:
      context: .
      dockerfile: Dockerfile-rotate
    ports:
      - 8082:8081
    env_file:
      - .env

  redis-rotate:
    networks:
      - api-net
    image: redis:7.2-rc-alpine
    restart: always
    container_name: redis-rotate
    ports:
      - '6380:6379'
    command: redis-server --save 20 1 --loglevel debug --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis-rotate-data:/data

#  minio-api:
#    networks:
#      - api-net
#    image: minio/minio:RELEASE.2024-02-14T21-36-02Z
#    container_name: minio-api
#    env_file:
#      - .env
#    command: server ~/minio --console-address :9090
#    ports:
#      - '9090:9090'
#      - '9000:9000'
#    volumes:
#      - minio-api-data:/minio

volumes:
#  minio-api-data:
  redis-rotate-data:
